import "../fonts/pixelmix.ttf";
import { SettingEntry, SettingValue, SettingType, SettingDatetime } from "screens/settings/types.slint";
import { FileListEntry } from "components/file_list.slint";

export enum ScreenId {
    MainMenu,
    RomSelect,
    Game,
    Settings,
    Tools,
    Error,
    About,
}

export struct BatteryInfo {
    vbus_pgood: bool,
    is_charging: bool,
    voltage: float,
    level: float,
    charge_rate: float,
}

export global Palette { }

export global Global {
    // Whether Home is currently pressed.
    in-out property <bool> home-pressed: false;
    // Whether the current pressing of Home was used for a shortcut key combo.
    in-out property <bool> home-consumed;
    out property <ScreenId> current-screen: MainMenu;
    // Whether the UI is transparent. Start true for the boot animation.
    in-out property <bool> ui-transparent: true;
    in-out property <bool> ui-status-bar: true;

    public function set-screen(screen: ScreenId) {
        current-screen = screen;
        ui-transparent = (screen == ScreenId.Game);
        Backend.screen-enter(screen);
    }
}

export global Backend {
    in property <string> device-serial;
    in property <int> device-revision;

    in-out property <bool> volume-visible: false;
    in-out property <int> volume-level: 50;
    in property <int> volume-increment: 5;

    in-out property <bool> brightness-visible: false;
    in-out property <int> brightness-level: 50;
    in property <int> brightness-increment: 5;

    in property <bool> status-is-saving: false;
    in property <int> battery-level: 11;

    in property <string> error-text: "";

    in property <int> rom-select-initial: 0;
    in-out property <int> rom-select-index: 0;
    in property <[FileListEntry]> rom-select-list: [];
    in property <string> rom-select-path: "/fake/path/";
    in property <percent> rom-select-progress: 0%;
    in property <bool> rom-select-is-loading: false;
    in-out property <string> rom-select-error;

    in property <[SettingEntry]> settings: [
        {
            name: "list",
            type: SettingType.list,
            choices: ["Low", "Medium", "High"],
            value: { int-value: 1 }
        },
        { name: "check 1", type: SettingType.checkbox, value: { bool-value: true } },
        { name: "check 2", type: SettingType.checkbox, value: { bool-value: false } },
        { name: "check 3", type: SettingType.checkbox, value: { bool-value: true } },
        { name: "subpage", type: SettingType.subpage },
        {
            name: "datetime",
            type: SettingType.datetime,
            value: { datetime-value: { year: 2024, month: 3, day: 31, hour: 9, min: 30 } }
        },
    ];

    callback volume-changed(int);
    callback brightness-changed(int);
    callback power-off();
    callback reboot();

    callback main-menu-run-cartridge();
    callback main-menu-load-rom();
    callback rom-select-selected(int) -> bool;
    callback rom-select-focused(int);
    callback rom-select-up() -> bool;
    callback game-set-paused(bool);
    callback game-reset();
    callback setting-changed(int, SettingValue);
    callback tools-start-usb-drive();
    callback tools-end-usb-drive();
    callback tools-get-battery-info() -> BatteryInfo;

    callback screen-enter(ScreenId);

    callback datetime-add(SettingDatetime, SettingDatetime) -> SettingDatetime;
}
