import { Icons } from "../../icons.slint";

export component ListBox {
    in-out property <int> index;
    in property <[string]> choices;
    in property <bool> selected;

    private property <length> item-height: i-area.viewport-height / choices.length;

    callback on-changed();

    HorizontalLayout {
        spacing: 2px;

        Image {
            source: Icons.left-caret;
            visible: selected && index > 0;
            colorize: #333;
        }

        i-area := Flickable {
            viewport-y: -root.item-height * root.index;
            viewport-height: i-items.min-height;
            height: item-height;
            width: i-items.min-width;

            i-items := VerticalLayout {
                width: self.min-width;
                for choice[i] in root.choices: child-items := Text {
                    text: choice;
                    horizontal-alignment: center;
                }
            }
        }

        Image {
            source: Icons.right-caret;
            visible: selected && index < choices.length - 1;
            colorize: #333;
        }
    }

    if selected: FocusScope {
        init => {
            self.focus();
        }
        key-pressed(event) => {
            if event.text == Key.LeftArrow {
                root.index = max(root.index - 1, 0);
                on-changed();
                return accept;
            }
            if event.text == Key.RightArrow {
                root.index = min(root.index + 1, root.choices.length - 1);
                on-changed();
                return accept;
            }
            reject
        }
    }
}
