name: Build ESP32 Firmware

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ESP32 Firmware
        uses: esp-rs/esp-idf-ci-action@v1
        with:
          target: esp32s3
          command: cargo build --release --manifest-path firmware/handheld/Cargo.toml
