package platform.handheld

import chisel3._
import chiseltest._
import org.scalatest.freespec.AnyFreeSpec

class DpiDriverSpec extends AnyFreeSpec with ChiselScalatestTester {
  "go" in {
    test(new DpiDriver(
      hActive = 20,
      hSync = 4,
      hBackPorch = 5,
      hFrontPorch = 6,
      vActive = 15,
      vSync = 1,
      vBackPorch = 2,
      vFrontPorch = 3,
    )) { dut =>
      for (y <- 0 until 21) {
        for (x <- 0 until 35) {
          if (dut.io.signals.enable.peekBoolean()) {
            print("*")
          } else if (dut.io.signals.hsync.peekBoolean() && dut.io.signals.vsync.peekBoolean()) {
            print("B")
          } else if (dut.io.signals.hsync.peekBoolean()) {
            print("H")
          } else if (dut.io.signals.vsync.peekBoolean()) {
            print("V")
          } else {
            print(".")
          }
          dut.clock.step()
        }
        println()
      }

      /*
      BBBBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
      HHHH...............................
      HHHH...............................
      HHHH.....********************......
      HHHH.....********************......
      HHHH.....********************......
      HHHH.....********************......
      HHHH.....********************......
      HHHH.....********************......
      HHHH.....********************......
      HHHH.....********************......
      HHHH.....********************......
      HHHH.....********************......
      HHHH.....********************......
      HHHH.....********************......
      HHHH.....********************......
      HHHH.....********************......
      HHHH.....********************......
      HHHH...............................
      HHHH...............................
      HHHH...............................
      */
    }
  }
}
